runtime: python310
entrypoint: gunicorn -b :$PORT main:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1

env_variables:
  OPENAI_API_KEY: ""

handlers:
- url: /
  static_files: templates/index.html
  upload: templates/index.html
- url: /.*
  script: auto